# Generated by Django 5.1.6 on 2025-02-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('package', models.IntegerField(choices=[(4, '4 aulas'), (8, '8 aulas'), (12, '12 aulas'), (16, '16 aulas'), (20, '20 aulas')])),
                ('payment_day', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('accumulated_classes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
            ],
        ),
    ]
