# Generated by Django 5.1.6 on 2025-02-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor da Mensalidade'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
